### ISSUE TITLE
Is the project maintained ?

### ISSUE THREAD

**Issue by sosher** [kennetek/gridfinity-rebuilt-openscad#199] opened 2024-07-02 12:12 UTC
this is really a very tentative question , And I appreciate deeply everything you did. but I was wondering if the project is still alive. 
Since the issue with the vase mode hasn't been resolved yet.
Again, Thanks very much and sorry in advance if this issue is insulting or anything.

**Comment by EmperorArthur** [comment] 2024-07-04 11:01
It appears to be maintained on and off.  For example, I have had a fix for Vase Mode in #181 since the end of April, but it hasn't been reviewed.

If you want the latest and greatest, I may start merging all my PRs into a "staging" branch and will point you there when I do so.

**Comment by sosher** [comment] 2024-07-10 04:03
That would be greatly appreciated , the fix for vase mode was the reason for this issue.
Again thanks

**Comment by Ruudjhuu** [comment] 2024-07-14 09:15
@EmperorArthur  if you are interested in helping to maintain this project I could contact @kennetek and add you as maintainer. I myself started hopeful. But it takes too much time to guard the regression of this project. Some pieces of code are tangled together (I think you improved this already by a lot) and without an easy to use testing framework in openscad, it takes a huge amount of effort to automate regression tests. 
There is also a setting which requires a review before any PR can be merged. It does not really work with the current activity of the maintainers. My own PRs were waiting while I could merge other changes which made it faster to integrate fixes by waiting till anyone but me fixed it. I lost interest as a maintainer this way.  This might change by changing the review setting or 2+ active maintainers. 

I also started a project with a python cad library myself which has regression testing and features of a more modern language. However, python is slow. But rendering in openscad is also slow.

**Comment by EmperorArthur** [comment] 2024-07-15 02:57
@Ruudjhuu please.  While I'm nowhere near perfect, I think I've broken enough to get a feel for regression testing and fixing things.

Its also why I ended up adding that Python image generation/ testing code to #187.  While it's not fully automated, it's at least a  convenient check.

Excluding the fit to drawer functionality, it's complete for baseplate testing.

**Comment by kennetek** [comment] 2024-07-22 22:20
Sorry all, I have been watching the repo from afar for a while now, the project has just grown faster than I can keep up and a lot of the code is unfamiliar to me now. I have seen you have done a lot of work @EmperorArthur over the past months, I think you definitely deserve to have merge permissions. Would be glad to see all your work get implemented and the issues/PR numbers go down. Thank you so much for your contributions.

**Comment by EmperorArthur** [comment] 2024-09-01 19:13
The answer is yes.  However, as is often the case, real life gets in the way.

**Closed by EmperorArthur** 2024-09-01 19:13 UTC
