### ISSUE TITLE
Printing errors and artifacts

### ISSUE THREAD

**Issue by Pytonballoon810** [kennetek/gridfinity-rebuilt-openscad#194] opened 2024-06-06 10:47 UTC
I created this bin using the minimal implementation:
![image](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/84274397/72277888-b9dd-4fe5-9bd6-95862ed08ea8)
and printed it twice and both look like this:
![IMG_20240606_124404754](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/84274397/a2d6096b-e700-4dbb-b01f-c9574d617b7c)
![IMG_20240606_124409542](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/84274397/7b608b9a-57f9-4ad5-a2ec-1ac227aaa4ef)
In the slicer it looks like this:
![image](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/84274397/8abd2dde-2df1-4e0c-875a-87be5af6465c)
the "closing layer" is also just this one top layer.

**Comment by EmperorArthur** [comment] 2024-06-15 05:41
Waiting for my spiral vase fix to be merged before I start down this rabbit hole.

**Comment by ch3vr0n5** [comment] 2024-06-18 13:46
This is interesting. I fixed this in a pull request months ago. #126 & #137 

I haven't pulled the latest changes since then, so my container looks like this:

![image](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/987282/b5143089-83eb-4f53-9b74-57cf9d03287c)

I'll have to pull the changes and see if this is a regression.

**Comment by EmperorArthur** [comment] 2024-06-27 02:58
> I'll have to pull the changes and see if this is a regression.

I completely re-did wall generation based on the Gridfinity spec, and I know it caused issues with Spiral vase mode.  #181

Depending on how the cutter for the lite bins is done, there may be some incompatibilities.  I do have test cases in my branches, and can add more for this as well.

**Closed** 2024-11-06 16:09 UTC
