### ISSUE TITLE
Radii and dimensions are not correct!

### ISSUE THREAD

**Issue by Bobbel93** [kennetek/gridfinity-rebuilt-openscad#165] opened 2024-02-08 20:40 UTC
Please check the exact dimensions again.

https://gridfinity.xyz/specification/

![IMG_6002](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/159487380/fe29fe16-d30e-4c06-853a-a824b115775e)

![IMG_6003](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/159487380/00f05696-9cfb-4741-be59-f67246431e5f)

**Comment by plaes** [comment] 2024-02-16 17:04
I can confirm that there is something incorrect, but I can't say what exactly:
https://github.com/kennetek/gridfinity-rebuilt-openscad/blob/2f2567d7a9f1672aa4d6d5cfe998cdb76db81b61/standard.scad#L12-L17

Firstly, descriptions for `r_fo1`, `r_fo2` and `r_fo3` are wrong, these are actually diameters (but they are correctly divided by two in the code). Comparing these values to gridfinity standard, then `r_fo1` should be changed to `7.5`.

And another suspicious variable seems to be `r_c2`:
```
// upper base chamfer "radius"
r_c2 = 1.4;  // should be 2.15 / 2 ?
```

**Comment by plaes** [comment] 2024-02-17 21:49
@Bobbel93 Please check #167

**Comment by EmperorArthur** [comment] 2024-02-26 05:30
Depending on how PR #171 goes, I will try using the same method to handle the edges of the bin.  That is:

* Creating a polygon of the enlarged profile, right next to what you have circled.
* Sweeping it along a path.

I have a suspicion that one of the reasons for your issues is the way `hull()` works.  The math for the base is reversed, and can be hard to read.  I started cleaning it up, but realized that just sweeping a path would give a better result that could be easily verified as matching the profile.

**Comment by EmperorArthur** [comment] 2024-03-11 03:38
Looks like half of #169 was actually a duplicate of this one.
I've moved that and the relevant screenshots here.

# Screenshots of issue in Freecad

## Commit 2f2567d
![2024-02-18 gridfinity-rebuilt-bins 1x1x6 (solid) FreeCAD - Commit 2f2567d](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/d0698a54-a2fd-454e-b42f-e2d97a6af96d)
![2024-02-18 gridfinity-rebuilt-bins 1x1x6 (solid) FreeCAD Zoomed In - Commit 2f2567d](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/7ba59578-a56d-4458-8df6-d9f6bdd0744f)

## Commit 5df8267
![2024-02-18 gridfinity-rebuilt-bins 1x1x6 (solid) FreeCAD Zoomed In Back - Commit 5df8267](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/293eea96-d57f-4719-afd8-61fbb3673f7c)
![2024-02-18 gridfinity-rebuilt-bins 1x1x6 (solid) FreeCAD Front - Commit 5df8267](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/b8269559-25ad-40ce-95fe-4c137190f757)
![2024-02-18 gridfinity-rebuilt-bins 1x1x6 (solid) FreeCAD Zoomed In Front - Commit 5df8267](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/6fff8d49-8a05-4ae2-a8ac-2e865a351893)

**Comment by EmperorArthur** [comment] 2024-03-11 03:51
@plaes and @Bobbel93 please check #171

I've re-created the profile based on the spec.  Which lead me to adjust `r_base` to equal `r_fo1`.

I have **not** checked if this works on the old code, but it fixes the issue in that PR.

![2024-01-25 Fixed Bin Radius](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/013a61ab-1682-4470-87e2-9bda0f65918c)

**Closed** 2024-04-18 18:07 UTC
