### ISSUE TITLE
Weird Cutouts in bin (using the lite-rebuild)

### ISSUE THREAD

**Issue by Pytonballoon810** [kennetek/gridfinity-rebuilt-openscad#225] opened 2024-09-30 15:22 UTC
Had this issue on the newest version of the rebuild. All settings included in the screenshots
Note that the height of the part itself is correct. I get 24.60 with .4mm layer heigth as i should be getting.

These are the settings i put in:
![Screenshot 2024-09-30 171808](https://github.com/user-attachments/assets/ada6097d-f2b1-4171-8492-7f6359b3305e)
![Screenshot 2024-09-30 171800](https://github.com/user-attachments/assets/4eb8cae7-fd04-421f-9346-666ab6c836f9)
After rendering it looks like this:
![Screenshot 2024-09-30 171454](https://github.com/user-attachments/assets/8163827f-cee6-4530-a774-0c7d31aca617)
![Screenshot 2024-09-30 171525](https://github.com/user-attachments/assets/87a1c6ce-e636-4886-aca1-9b622ec5758a)
In the slicer it looks like this:
![Screenshot 2024-09-30 171535](https://github.com/user-attachments/assets/4813d20a-401a-4441-9503-e3340bb72633)

**Comment by tobymurray** [comment] 2024-10-04 13:19
Looks like this is the same as https://github.com/kennetek/gridfinity-rebuilt-openscad/issues/224

**Comment by EmperorArthur** [comment] 2024-10-06 17:42
I see the issue, and am working on fixing it.

**Comment by EmperorArthur** [comment] 2024-10-13 19:27
Closing as a duplicate of #224.

I am actively working the issue.

**Closed by EmperorArthur** 2024-10-13 19:27 UTC
