### ISSUE TITLE
Magnet holes do not get generated

### ISSUE THREAD

**Issue by geekifier** [kennetek/gridfinity-rebuilt-openscad#79] opened 2023-02-24 18:43 UTC
**Update**: Comparing this with the baseplates from https://github.com/vector76/gridfinity_openscad, the magnets holes in _this_ project simply don't get generated with any baseplate style. In the linked project, the magnet holes are generated ON TOP of the baseplate, without screw holes.

Toggling the magnet holes on/off makes the baseplate thicker, but still no magnet holes.
I tried both with the latest release of OpenSCAD, as well as with the DEV snapshot, same results. 

I am attaching an STL exported with the following options:

```
OpenSCAD: 2023.02.15
$fa: 8
$fs: 0.25
gridx: 1
gridy: 1
length: 42

d screw: 3.35
d screw head 5
screw spacing: 0.5
n screws: 1

style plate: skeletonized
enable  magnet hole: true
style hole: counterbore

# second STL I generated with 
style hole: none
```

STL with `enable  magnet hole: true` and `style hole: counterbore`:
[skeletonized-counter-magnet-test.zip](https://github.com/kennetek/gridfinity-rebuilt-openscad/files/10827886/skeletonized-counter-magnet-test.zip)

STL with `enable  magnet hole: true` and `style hole: none`:
[skeletonized-nohole-magnet-test.zip](https://github.com/kennetek/gridfinity-rebuilt-openscad/files/10827962/skeletonized-nohole-magnet-test.zip)

**Comment by Ruudjhuu** [comment] 2023-02-25 17:11
Duplicate of #77

**Closed** 2023-03-17 17:21 UTC
